### PR TITLE
IAC script for mynodeapp

### PR DESCRIPTION
**Pull request by AshuApurva14**
I have added terraform code for mynodeapp. Request to please check and review in order to merge.

### CODE REVIEW

**Review by Kundankkrishna — CHANGES_REQUESTED** [review]
Kindly use the github actions suggested step for docker login.

**Review by Kundankkrishna — COMMENTED** [review]
Thank you for your input Ashutosh, this change is looking good but the app will not be deployed on the specified infra therefore won't be merged to the main code, but I really appreciate the work and thank you for the input.

**Comment by Kundankkrishna** [comment]
the app will not be deployed on the specified infra therefore won't be merged to the main code.

**Comment by AshuApurva14** [comment]
Thanks for your confirmation.

**Pull request closed without merging**
